// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor.proto

package com.example.iot.proto;

public final class SensorProtos {
  private SensorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SensorDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.iot.proto.SensorData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    java.lang.String getDeviceId();
    /**
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
     * @return Whether the metrics field is set.
     */
    boolean hasMetrics();
    /**
     * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
     * @return The metrics.
     */
    com.example.iot.proto.SensorProtos.SensorData.Metrics getMetrics();
    /**
     * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
     */
    com.example.iot.proto.SensorProtos.SensorData.MetricsOrBuilder getMetricsOrBuilder();
  }
  /**
   * Protobuf type {@code com.example.iot.proto.SensorData}
   */
  public static final class SensorData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.iot.proto.SensorData)
      SensorDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SensorData.newBuilder() to construct.
    private SensorData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SensorData() {
      deviceId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SensorData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SensorData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 16: {

              timestamp_ = input.readInt64();
              break;
            }
            case 26: {
              com.example.iot.proto.SensorProtos.SensorData.Metrics.Builder subBuilder = null;
              if (metrics_ != null) {
                subBuilder = metrics_.toBuilder();
              }
              metrics_ = input.readMessage(com.example.iot.proto.SensorProtos.SensorData.Metrics.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(metrics_);
                metrics_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.iot.proto.SensorProtos.internal_static_com_example_iot_proto_SensorData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.iot.proto.SensorProtos.internal_static_com_example_iot_proto_SensorData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.iot.proto.SensorProtos.SensorData.class, com.example.iot.proto.SensorProtos.SensorData.Builder.class);
    }

    public interface MetricsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.example.iot.proto.SensorData.Metrics)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>float temperature = 1;</code>
       * @return The temperature.
       */
      float getTemperature();

      /**
       * <code>float humidity = 2;</code>
       * @return The humidity.
       */
      float getHumidity();
    }
    /**
     * Protobuf type {@code com.example.iot.proto.SensorData.Metrics}
     */
    public static final class Metrics extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.example.iot.proto.SensorData.Metrics)
        MetricsOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Metrics.newBuilder() to construct.
      private Metrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Metrics() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Metrics();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Metrics(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {

                temperature_ = input.readFloat();
                break;
              }
              case 21: {

                humidity_ = input.readFloat();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.iot.proto.SensorProtos.internal_static_com_example_iot_proto_SensorData_Metrics_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.iot.proto.SensorProtos.internal_static_com_example_iot_proto_SensorData_Metrics_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.iot.proto.SensorProtos.SensorData.Metrics.class, com.example.iot.proto.SensorProtos.SensorData.Metrics.Builder.class);
      }

      public static final int TEMPERATURE_FIELD_NUMBER = 1;
      private float temperature_;
      /**
       * <code>float temperature = 1;</code>
       * @return The temperature.
       */
      @java.lang.Override
      public float getTemperature() {
        return temperature_;
      }

      public static final int HUMIDITY_FIELD_NUMBER = 2;
      private float humidity_;
      /**
       * <code>float humidity = 2;</code>
       * @return The humidity.
       */
      @java.lang.Override
      public float getHumidity() {
        return humidity_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (temperature_ != 0F) {
          output.writeFloat(1, temperature_);
        }
        if (humidity_ != 0F) {
          output.writeFloat(2, humidity_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (temperature_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(1, temperature_);
        }
        if (humidity_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, humidity_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.example.iot.proto.SensorProtos.SensorData.Metrics)) {
          return super.equals(obj);
        }
        com.example.iot.proto.SensorProtos.SensorData.Metrics other = (com.example.iot.proto.SensorProtos.SensorData.Metrics) obj;

        if (java.lang.Float.floatToIntBits(getTemperature())
            != java.lang.Float.floatToIntBits(
                other.getTemperature())) return false;
        if (java.lang.Float.floatToIntBits(getHumidity())
            != java.lang.Float.floatToIntBits(
                other.getHumidity())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getTemperature());
        hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getHumidity());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.example.iot.proto.SensorProtos.SensorData.Metrics parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.example.iot.proto.SensorProtos.SensorData.Metrics prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.example.iot.proto.SensorData.Metrics}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.example.iot.proto.SensorData.Metrics)
          com.example.iot.proto.SensorProtos.SensorData.MetricsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.example.iot.proto.SensorProtos.internal_static_com_example_iot_proto_SensorData_Metrics_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.example.iot.proto.SensorProtos.internal_static_com_example_iot_proto_SensorData_Metrics_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.example.iot.proto.SensorProtos.SensorData.Metrics.class, com.example.iot.proto.SensorProtos.SensorData.Metrics.Builder.class);
        }

        // Construct using com.example.iot.proto.SensorProtos.SensorData.Metrics.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          temperature_ = 0F;

          humidity_ = 0F;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.example.iot.proto.SensorProtos.internal_static_com_example_iot_proto_SensorData_Metrics_descriptor;
        }

        @java.lang.Override
        public com.example.iot.proto.SensorProtos.SensorData.Metrics getDefaultInstanceForType() {
          return com.example.iot.proto.SensorProtos.SensorData.Metrics.getDefaultInstance();
        }

        @java.lang.Override
        public com.example.iot.proto.SensorProtos.SensorData.Metrics build() {
          com.example.iot.proto.SensorProtos.SensorData.Metrics result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.example.iot.proto.SensorProtos.SensorData.Metrics buildPartial() {
          com.example.iot.proto.SensorProtos.SensorData.Metrics result = new com.example.iot.proto.SensorProtos.SensorData.Metrics(this);
          result.temperature_ = temperature_;
          result.humidity_ = humidity_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.example.iot.proto.SensorProtos.SensorData.Metrics) {
            return mergeFrom((com.example.iot.proto.SensorProtos.SensorData.Metrics)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.example.iot.proto.SensorProtos.SensorData.Metrics other) {
          if (other == com.example.iot.proto.SensorProtos.SensorData.Metrics.getDefaultInstance()) return this;
          if (other.getTemperature() != 0F) {
            setTemperature(other.getTemperature());
          }
          if (other.getHumidity() != 0F) {
            setHumidity(other.getHumidity());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.example.iot.proto.SensorProtos.SensorData.Metrics parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.example.iot.proto.SensorProtos.SensorData.Metrics) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private float temperature_ ;
        /**
         * <code>float temperature = 1;</code>
         * @return The temperature.
         */
        @java.lang.Override
        public float getTemperature() {
          return temperature_;
        }
        /**
         * <code>float temperature = 1;</code>
         * @param value The temperature to set.
         * @return This builder for chaining.
         */
        public Builder setTemperature(float value) {
          
          temperature_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float temperature = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearTemperature() {
          
          temperature_ = 0F;
          onChanged();
          return this;
        }

        private float humidity_ ;
        /**
         * <code>float humidity = 2;</code>
         * @return The humidity.
         */
        @java.lang.Override
        public float getHumidity() {
          return humidity_;
        }
        /**
         * <code>float humidity = 2;</code>
         * @param value The humidity to set.
         * @return This builder for chaining.
         */
        public Builder setHumidity(float value) {
          
          humidity_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float humidity = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearHumidity() {
          
          humidity_ = 0F;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.example.iot.proto.SensorData.Metrics)
      }

      // @@protoc_insertion_point(class_scope:com.example.iot.proto.SensorData.Metrics)
      private static final com.example.iot.proto.SensorProtos.SensorData.Metrics DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.example.iot.proto.SensorProtos.SensorData.Metrics();
      }

      public static com.example.iot.proto.SensorProtos.SensorData.Metrics getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Metrics>
          PARSER = new com.google.protobuf.AbstractParser<Metrics>() {
        @java.lang.Override
        public Metrics parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Metrics(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Metrics> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Metrics> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.example.iot.proto.SensorProtos.SensorData.Metrics getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceId_;
    /**
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int METRICS_FIELD_NUMBER = 3;
    private com.example.iot.proto.SensorProtos.SensorData.Metrics metrics_;
    /**
     * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
     * @return Whether the metrics field is set.
     */
    @java.lang.Override
    public boolean hasMetrics() {
      return metrics_ != null;
    }
    /**
     * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
     * @return The metrics.
     */
    @java.lang.Override
    public com.example.iot.proto.SensorProtos.SensorData.Metrics getMetrics() {
      return metrics_ == null ? com.example.iot.proto.SensorProtos.SensorData.Metrics.getDefaultInstance() : metrics_;
    }
    /**
     * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
     */
    @java.lang.Override
    public com.example.iot.proto.SensorProtos.SensorData.MetricsOrBuilder getMetricsOrBuilder() {
      return getMetrics();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (metrics_ != null) {
        output.writeMessage(3, getMetrics());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (metrics_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMetrics());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.iot.proto.SensorProtos.SensorData)) {
        return super.equals(obj);
      }
      com.example.iot.proto.SensorProtos.SensorData other = (com.example.iot.proto.SensorProtos.SensorData) obj;

      if (!getDeviceId()
          .equals(other.getDeviceId())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (hasMetrics() != other.hasMetrics()) return false;
      if (hasMetrics()) {
        if (!getMetrics()
            .equals(other.getMetrics())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      if (hasMetrics()) {
        hash = (37 * hash) + METRICS_FIELD_NUMBER;
        hash = (53 * hash) + getMetrics().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.iot.proto.SensorProtos.SensorData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.iot.proto.SensorProtos.SensorData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.iot.proto.SensorProtos.SensorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.iot.proto.SensorProtos.SensorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.iot.proto.SensorProtos.SensorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.iot.proto.SensorProtos.SensorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.iot.proto.SensorProtos.SensorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.iot.proto.SensorProtos.SensorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.iot.proto.SensorProtos.SensorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.iot.proto.SensorProtos.SensorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.iot.proto.SensorProtos.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.iot.proto.SensorProtos.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.iot.proto.SensorProtos.SensorData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.iot.proto.SensorData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.iot.proto.SensorData)
        com.example.iot.proto.SensorProtos.SensorDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.iot.proto.SensorProtos.internal_static_com_example_iot_proto_SensorData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.iot.proto.SensorProtos.internal_static_com_example_iot_proto_SensorData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.iot.proto.SensorProtos.SensorData.class, com.example.iot.proto.SensorProtos.SensorData.Builder.class);
      }

      // Construct using com.example.iot.proto.SensorProtos.SensorData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        timestamp_ = 0L;

        if (metricsBuilder_ == null) {
          metrics_ = null;
        } else {
          metrics_ = null;
          metricsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.iot.proto.SensorProtos.internal_static_com_example_iot_proto_SensorData_descriptor;
      }

      @java.lang.Override
      public com.example.iot.proto.SensorProtos.SensorData getDefaultInstanceForType() {
        return com.example.iot.proto.SensorProtos.SensorData.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.iot.proto.SensorProtos.SensorData build() {
        com.example.iot.proto.SensorProtos.SensorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.iot.proto.SensorProtos.SensorData buildPartial() {
        com.example.iot.proto.SensorProtos.SensorData result = new com.example.iot.proto.SensorProtos.SensorData(this);
        result.deviceId_ = deviceId_;
        result.timestamp_ = timestamp_;
        if (metricsBuilder_ == null) {
          result.metrics_ = metrics_;
        } else {
          result.metrics_ = metricsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.iot.proto.SensorProtos.SensorData) {
          return mergeFrom((com.example.iot.proto.SensorProtos.SensorData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.iot.proto.SensorProtos.SensorData other) {
        if (other == com.example.iot.proto.SensorProtos.SensorData.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasMetrics()) {
          mergeMetrics(other.getMetrics());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.iot.proto.SensorProtos.SensorData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.iot.proto.SensorProtos.SensorData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <code>string device_id = 1;</code>
       * @return The deviceId.
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_id = 1;</code>
       * @return The bytes for deviceId.
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_id = 1;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string device_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string device_id = 1;</code>
       * @param value The bytes for deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.example.iot.proto.SensorProtos.SensorData.Metrics metrics_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.iot.proto.SensorProtos.SensorData.Metrics, com.example.iot.proto.SensorProtos.SensorData.Metrics.Builder, com.example.iot.proto.SensorProtos.SensorData.MetricsOrBuilder> metricsBuilder_;
      /**
       * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
       * @return Whether the metrics field is set.
       */
      public boolean hasMetrics() {
        return metricsBuilder_ != null || metrics_ != null;
      }
      /**
       * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
       * @return The metrics.
       */
      public com.example.iot.proto.SensorProtos.SensorData.Metrics getMetrics() {
        if (metricsBuilder_ == null) {
          return metrics_ == null ? com.example.iot.proto.SensorProtos.SensorData.Metrics.getDefaultInstance() : metrics_;
        } else {
          return metricsBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
       */
      public Builder setMetrics(com.example.iot.proto.SensorProtos.SensorData.Metrics value) {
        if (metricsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metrics_ = value;
          onChanged();
        } else {
          metricsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
       */
      public Builder setMetrics(
          com.example.iot.proto.SensorProtos.SensorData.Metrics.Builder builderForValue) {
        if (metricsBuilder_ == null) {
          metrics_ = builderForValue.build();
          onChanged();
        } else {
          metricsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
       */
      public Builder mergeMetrics(com.example.iot.proto.SensorProtos.SensorData.Metrics value) {
        if (metricsBuilder_ == null) {
          if (metrics_ != null) {
            metrics_ =
              com.example.iot.proto.SensorProtos.SensorData.Metrics.newBuilder(metrics_).mergeFrom(value).buildPartial();
          } else {
            metrics_ = value;
          }
          onChanged();
        } else {
          metricsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
       */
      public Builder clearMetrics() {
        if (metricsBuilder_ == null) {
          metrics_ = null;
          onChanged();
        } else {
          metrics_ = null;
          metricsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
       */
      public com.example.iot.proto.SensorProtos.SensorData.Metrics.Builder getMetricsBuilder() {
        
        onChanged();
        return getMetricsFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
       */
      public com.example.iot.proto.SensorProtos.SensorData.MetricsOrBuilder getMetricsOrBuilder() {
        if (metricsBuilder_ != null) {
          return metricsBuilder_.getMessageOrBuilder();
        } else {
          return metrics_ == null ?
              com.example.iot.proto.SensorProtos.SensorData.Metrics.getDefaultInstance() : metrics_;
        }
      }
      /**
       * <code>.com.example.iot.proto.SensorData.Metrics metrics = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.iot.proto.SensorProtos.SensorData.Metrics, com.example.iot.proto.SensorProtos.SensorData.Metrics.Builder, com.example.iot.proto.SensorProtos.SensorData.MetricsOrBuilder> 
          getMetricsFieldBuilder() {
        if (metricsBuilder_ == null) {
          metricsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.iot.proto.SensorProtos.SensorData.Metrics, com.example.iot.proto.SensorProtos.SensorData.Metrics.Builder, com.example.iot.proto.SensorProtos.SensorData.MetricsOrBuilder>(
                  getMetrics(),
                  getParentForChildren(),
                  isClean());
          metrics_ = null;
        }
        return metricsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.iot.proto.SensorData)
    }

    // @@protoc_insertion_point(class_scope:com.example.iot.proto.SensorData)
    private static final com.example.iot.proto.SensorProtos.SensorData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.iot.proto.SensorProtos.SensorData();
    }

    public static com.example.iot.proto.SensorProtos.SensorData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SensorData>
        PARSER = new com.google.protobuf.AbstractParser<SensorData>() {
      @java.lang.Override
      public SensorData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SensorData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SensorData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.iot.proto.SensorProtos.SensorData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_iot_proto_SensorData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_iot_proto_SensorData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_iot_proto_SensorData_Metrics_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_iot_proto_SensorData_Metrics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sensor.proto\022\025com.example.iot.proto\"\240\001" +
      "\n\nSensorData\022\021\n\tdevice_id\030\001 \001(\t\022\021\n\ttimes" +
      "tamp\030\002 \001(\003\022:\n\007metrics\030\003 \001(\0132).com.exampl" +
      "e.iot.proto.SensorData.Metrics\0320\n\007Metric" +
      "s\022\023\n\013temperature\030\001 \001(\002\022\020\n\010humidity\030\002 \001(\002" +
      "B%\n\025com.example.iot.protoB\014SensorProtosb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_iot_proto_SensorData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_iot_proto_SensorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_iot_proto_SensorData_descriptor,
        new java.lang.String[] { "DeviceId", "Timestamp", "Metrics", });
    internal_static_com_example_iot_proto_SensorData_Metrics_descriptor =
      internal_static_com_example_iot_proto_SensorData_descriptor.getNestedTypes().get(0);
    internal_static_com_example_iot_proto_SensorData_Metrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_iot_proto_SensorData_Metrics_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
